server:
  servlet:
    session:
      timeout: 1h

spring:
  datasource:
    url: jdbc:postgresql://${host}:5432/${database}
    username:
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
    
license-server:
  message: "Welcome to license-server"
    
